<?php
/**
 * @file
 * jfm module file
 */

require_once 'jfm.core.inc';

function jfm_theme($existing, $type, $theme, $path) {
  $theme = array(
    'social_bar' => array(
      'template' => 'social-bar',
      'path' => drupal_get_path('module', 'jfm') . '/tpl'
    ),
  );

  return $theme;

}
/**
 *  Implements hook_block_info()
 */
function jfm_block_info() {
  module_load_include('inc', 'jfm', 'inc/block.info');
  $blocks = array();
  $blocks['social_bar'] = getSocialBarInfo();

  return $blocks;
}
/**
 *  Implements hook_block_view()
 */
function jfm_block_view($delta = '') {
  module_load_include('inc', 'jfm', 'inc/block.view');
  $block = array();
  $block['content'] = getThemeSocialBar($delta);
  return $block;
}